const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    gptSearch: "GPT Search",
    homePage: "HomePage",
    signOut: "Sign Out",
    signIn: "Sign In",
    signUp: "Sign Up",
    emailPlaceholder: "Email or phone number",
    passwordPlaceholder: "Password",
    fullNamePlaceholder: "Full Name",
    signUpPrompt: "New to Netflix? Sign Up Now.",
    signInPrompt: "Already registered? Sign In Now.",
    nowPlayingMovies: "Now Playing Movies",
    popularMovies: "Popular Movies",
    topRatedMovies: "Top Rated Movies",
    upcomingMovies: "Upcoming Movies",
    airingTodayTvSeries: "Airing Today TV Series",
    onTheAirTvSeries: "On The Air TV Series",
    popularTvSeries: "Popular TV Series",
    topRatedTvSeries: "Top Rated TV Series",
    play: "Play",
    moreInfo: "More Info",
    tailorYourBinge: "Tailor Your Binge",
    sortBy: "Sort By",
    genres: "Genres",
    results: "Results",
    allYears: "All Years",
    year: "Year",
    popularity: "Popularity",
    releaseDate: "Release Date",
    revenue: "Revenue",
    topRated: "Top Rated",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    gptSearch: "जीपीटी खोज",
    homePage: "होमपेज",
    signOut: "साइन आउट",
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    emailPlaceholder: "ईमेल या फ़ोन नंबर",
    passwordPlaceholder: "पासवर्ड",
    fullNamePlaceholder: "पूरा नाम",
    signUpPrompt: "नेटफ्लिक्स पर नए हैं? अभी साइन अप करें।",
    signInPrompt: "पहले से पंजीकृत हैं? अभी साइन इन करें।",
    nowPlayingMovies: "अभी चल रही फिल्में",
    popularMovies: "लोकप्रिय फिल्में",
    topRatedMovies: "टॉप रेटेड फिल्में",
    upcomingMovies: "आने वाली फिल्में",
    airingTodayTvSeries: "आज प्रसारित हो रही टीवी श्रृंखला",
    onTheAirTvSeries: "ऑन द एयर टीवी श्रृंखला",
    popularTvSeries: "लोकप्रिय टीवी श्रृंखला",
    topRatedTvSeries: "टॉप रेटेड टीवी श्रृंखला",
    play: "चलाएं",
    moreInfo: "और जानकारी",
    tailorYourBinge: "अपनी पसंद से देखें",
    sortBy: "इसके अनुसार छांटे",
    genres: "शैलियाँ",
    results: "परिणाम",
    allYears: "सभी वर्ष",
    year: "वर्ष",
    popularity: "लोकप्रियता",
    releaseDate: "रिलीज़ की तारीख",
    revenue: "राजस्व",
    topRated: "टॉप रेटेड",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    gptSearch: "Búsqueda GPT",
    homePage: "Página de inicio",
    signOut: "Cerrar sesión",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    emailPlaceholder: "Email o número de teléfono",
    passwordPlaceholder: "Contraseña",
    fullNamePlaceholder: "Nombre completo",
    signUpPrompt: "¿Nuevo en Netflix? Regístrate ahora.",
    signInPrompt: "¿Ya estás registrado? Inicia sesión ahora.",
    nowPlayingMovies: "Películas en cartelera",
    popularMovies: "Películas populares",
    topRatedMovies: "Películas mejor valoradas",
    upcomingMovies: "Próximas películas",
    airingTodayTvSeries: "Series de TV en emisión hoy",
    onTheAirTvSeries: "Series de TV en el aire",
    popularTvSeries: "Series de TV populares",
    topRatedTvSeries: "Series de TV mejor valoradas",
    play: "Reproducir",
    moreInfo: "Más información",
    tailorYourBinge: "Personaliza tu maratón",
    sortBy: "Ordenar por",
    genres: "Géneros",
    results: "Resultados",
    allYears: "Todos los años",
    year: "Año",
    popularity: "Popularidad",
    releaseDate: "Fecha de lanzamiento",
    revenue: "Ingresos",
    topRated: "Mejor valoradas",
  },
  fr: {
    search: "Rechercher",
    gptSearchPlaceholder: "Qu’aimeriez-vous regarder aujourd’hui ?",
    gptSearch: "Recherche GPT",
    homePage: "Accueil",
    signOut: "Déconnexion",
    signIn: "S'identifier",
    signUp: "S'inscrire",
    emailPlaceholder: "Adresse e-mail ou numéro de téléphone",
    passwordPlaceholder: "Mot de passe",
    fullNamePlaceholder: "Nom complet",
    signUpPrompt: "Nouveau sur Netflix ? Inscrivez-vous maintenant.",
    signInPrompt: "Déjà inscrit ? S'identifier.",
    nowPlayingMovies: "Films en cours de lecture",
    popularMovies: "Films populaires",
    topRatedMovies: "Films les mieux notés",
    upcomingMovies: "Films à venir",
    airingTodayTvSeries: "Séries TV diffusées aujourd'hui",
    onTheAirTvSeries: "Séries TV à l'antenne",
    popularTvSeries: "Séries TV populaires",
    topRatedTvSeries: "Séries TV les mieux notées",
    play: "Lecture",
    moreInfo: "Plus d'infos",
    tailorYourBinge: "Personnalisez votre binge",
    sortBy: "Trier par",
    genres: "Genres",
    results: "Résultats",
    allYears: "Toutes les années",
    year: "Année",
    popularity: "Popularité",
    releaseDate: "Date de sortie",
    revenue: "Revenus",
    topRated: "Les mieux notés",
  },
  de: {
    search: "Suchen",
    gptSearchPlaceholder: "Was möchtest du heute sehen?",
    gptSearch: "GPT-Suche",
    homePage: "Startseite",
    signOut: "Abmelden",
    signIn: "Einloggen",
    signUp: "Registrieren",
    emailPlaceholder: "E-Mail-Adresse oder Telefonnummer",
    passwordPlaceholder: "Passwort",
    fullNamePlaceholder: "Vollständiger Name",
    signUpPrompt: "Neu bei Netflix? Jetzt registrieren.",
    signInPrompt: "Bereits registriert? Jetzt einloggen.",
    nowPlayingMovies: "Aktuelle Filme",
    popularMovies: "Beliebte Filme",
    topRatedMovies: "Top-bewertete Filme",
    upcomingMovies: "Kommende Filme",
    airingTodayTvSeries: "Heute ausgestrahlte Fernsehserien",
    onTheAirTvSeries: "Laufende Fernsehserien",
    popularTvSeries: "Beliebte Fernsehserien",
    topRatedTvSeries: "Top-bewertete Fernsehserien",
    play: "Abspielen",
    moreInfo: "Mehr Infos",
    tailorYourBinge: "Deinen Binge anpassen",
    sortBy: "Sortieren nach",
    genres: "Genres",
    results: "Ergebnisse",
    allYears: "Alle Jahre",
    year: "Jahr",
    popularity: "Beliebtheit",
    releaseDate: "Veröffentlichungsdatum",
    revenue: "Einnahmen",
    topRated: "Am besten bewertet",
  },
  it: {
    search: "Cerca",
    gptSearchPlaceholder: "Cosa ti piacerebbe guardare oggi?",
    gptSearch: "Ricerca GPT",
    homePage: "Homepage",
    signOut: "Esci",
    signIn: "Accedi",
    signUp: "Registrati",
    emailPlaceholder: "Email o numero di telefono",
    passwordPlaceholder: "Password",
    fullNamePlaceholder: "Nome completo",
    signUpPrompt: "Nuovo su Netflix? Registrati ora.",
    signInPrompt: "Già registrato? Accedi.",
    nowPlayingMovies: "Film in programmazione",
    popularMovies: "Film popolari",
    topRatedMovies: "Film più votati",
    upcomingMovies: "Film in uscita",
    airingTodayTvSeries: "Serie TV in onda oggi",
    onTheAirTvSeries: "Serie TV in onda",
    popularTvSeries: "Serie TV popolari",
    topRatedTvSeries: "Serie TV più votate",
    play: "Riproduci",
    moreInfo: "Più info",
    tailorYourBinge: "Personalizza la tua maratona",
    sortBy: "Ordina per",
    genres: "Generi",
    results: "Risultati",
    allYears: "Tutti gli anni",
    year: "Anno",
    popularity: "Popolarità",
    releaseDate: "Data di rilascio",
    revenue: "Ricavi",
    topRated: "I più votati",
  },
};

export default lang;
